apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: px-high-rf2
  labels:
    app: prometheus
    component: core
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
